[unix_http_server]
file=/tmp/agent-supervisor.sock

[supervisord]
logfile=/home/alansrobotlab/lloyd/agent-services/logs/supervisord.log
pidfile=/tmp/agent-supervisord.pid
nodaemon=false
user=alansrobotlab

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/agent-supervisor.sock

[include]
files = /home/alansrobotlab/lloyd/agent-services/supervisor/conf.d/*.conf
