#!/usr/bin/env python3
"""
Nightly Deep Extraction - Next-Gen Memory System

Runs at 2 AM PST with the primary model for comprehensive extraction.
"""

import argparse
import json
import os
import sys
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path

# Content hashing for incremental processing
sys.path.insert(0, str(Path.home() / "lloyd" / "scripts" / "memory"))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent.parent))
from app.atomic_io import hash_bytes  # noqa: E402
from fact_extractor import ExtractionFailed  # noqa: E402

try:
    from content_hasher import ContentHasher
    _HAS_HASHER = True
except ImportError:
    _HAS_HASHER = False

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent.parent))
from app.paths import VAULT_FACTS_ROOT as FACTS_DIR
VAULT = Path.home() / "obsidian"
MEMORY_DIR = VAULT / "memory"
INDEX_FILE = Path(__file__).resolve().parent.parent.parent.parent / "_pipeline" / "relations-index.json"

# Import local modules
sys.path.insert(0, str(VAULT / "agents" / "memory" / "scripts" / "next-gen-memory"))

from fact_extractor import FactExtractor
from relations_index import RelationsIndexGenerator
from profile_generator import ProfileGenerator


_SELF_WRITTEN_MEMORY_NOTES = frozenset({
    # Derived indexes regenerated by the pipeline itself every cycle.
    "semantic-relationships.md",
    "relationship-proposals.md",
    "skills-index.md",
})


CONFIG_PATH = Path(__file__).resolve().parent / "pipeline_config.yaml"


def _load_pipeline_config() -> dict:
    """Read pipeline_config.yaml. It existed since 2026-07 and nothing read it."""
    try:
        data = yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8")) or {}
    except FileNotFoundError:
        raise RuntimeError(f"pipeline_config.yaml not found at {CONFIG_PATH}")
    except Exception as e:
        raise RuntimeError(f"pipeline_config.yaml is unreadable: {e}") from e
    if not isinstance(data, dict):
        raise RuntimeError("pipeline_config.yaml did not parse to a mapping")
    return data


def _TODAY_STR() -> str:
    return datetime.now().strftime("%Y-%m-%d")


class NightlyExtraction:
    """Nightly deep extraction with primary model."""

    def __init__(self):
        self.extractor = FactExtractor(model_port=8096)  # Uses primary for deep extraction
        self.rel_generator = RelationsIndexGenerator()
        self.profile_generator = ProfileGenerator(model_port=8096)
        self.log_file = Path.home() / "lloyd" / "_pipeline" / "nightly-extraction.log"
        # Thread-safe locks per entity for parallel processing
        self.entity_locks = {}
        self.locks_lock = threading.Lock()
    
    def _get_entity_lock(self, entity: str) -> threading.Lock:
        """Get or create a lock for an entity."""
        with self.locks_lock:
            if entity not in self.entity_locks:
                self.entity_locks[entity] = threading.Lock()
            return self.entity_locks[entity]
    
    # Files under FACTS_DIR that a clean must NEVER delete. On 2026-08-22 this
    # method wiped the fact tree and took `_relationships.json` (12,131 edges /
    # 7,260 active) and the `memory-graph/` working directory with it. Fact
    # content is derivable from the vault; the EDGE GRAPH, merge history and
    # hand-review state are not — they were built incrementally by the v4
    # classifier and successive resolution sweeps. There was no backup: this
    # tree is gitignored and nothing else copies it. Tasks #48, #67, #69 and
    # #74 have been blocked ever since.
    PROTECTED_NAMES = frozenset({
        "entity-registry.json",
        "_relationships.json",
        "entity-aliases.json",
    })
    PROTECTED_DIRS = frozenset({"templates", "memory-graph"})

    def _is_protected(self, item) -> bool:
        if item.name in self.PROTECTED_NAMES or item.name in self.PROTECTED_DIRS:
            return True
        # Backups and snapshots of the above (…​.bak, .bak.json, .corrupt-*.bak,
        # _relationships.<ts>.bak.json) are the only recovery path there is.
        lowered = item.name.lower()
        return ".bak" in lowered or lowered.startswith("_relationships")

    def backup_graph_state(self):
        """Timestamped copy of the irreplaceable files before a destructive pass."""
        import shutil
        stamp = datetime.now().strftime("%Y%m%dT%H%M%SZ")
        dest = Path.home() / "lloyd" / "_pipeline" / "backups" / f"pre-clean-{stamp}"
        saved = []
        for name in ("_relationships.json", "entity-aliases.json"):
            src = FACTS_DIR / name
            if src.is_file():
                dest.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dest / name)
                saved.append(name)
        graph_dir = Path.home() / "lloyd" / "_pipeline" / "memory-graph"
        if graph_dir.is_dir() and any(graph_dir.iterdir()):
            dest.mkdir(parents=True, exist_ok=True)
            shutil.copytree(graph_dir, dest / "memory-graph", dirs_exist_ok=True)
            saved.append("memory-graph/")
        if saved:
            print(f"  → Backed up {', '.join(saved)} to {dest}")
        return dest if saved else None

    def clean_facts_directory(self):
        """Wipe the entity tree, preserving the graph and its backups."""
        if not FACTS_DIR.exists():
            print("  → Facts directory does not exist, skipping clean")
            return

        self.backup_graph_state()

        removed = kept = 0
        for item in FACTS_DIR.iterdir():
            if self._is_protected(item):
                kept += 1
                continue
            if item.is_dir():
                import shutil
                shutil.rmtree(item)
            else:
                item.unlink()
            removed += 1

        print(f"  → Facts directory cleaned ({removed} removed, "
              f"{kept} protected entries kept)")
    
    def run_full_extraction(self, full_mode=False, workers=1, clean=False, limit=0, force=False):
        """Run complete nightly extraction pipeline."""
        start_time = datetime.now()
        log_lines = [
            f"\n{'='*60}",
            f"Nightly Extraction Started: {start_time.isoformat()}",
            f"Mode: {'Full Vault' if full_mode else '24h Window'}",
            f"Workers: {workers}",
            f"Clean: {'Yes' if clean else 'No'}",
            f"{'='*60}"
        ]
        
        try:
            # Clean facts directory if requested
            if clean:
                log_lines.append("\n[Pre-Flight] Cleaning Facts Directory")
                self.clean_facts_directory()
            
            # Step 1: Full vault fact extraction. Duplicate detection moved to
            # kg_hygiene.near_duplicates, which measures the same thing without
            # a per-run 23k-directory scan whose only output was a log line.
            log_lines.append("\n[Step 1] Full Vault Fact Extraction")
            self.last_files_processed = 0
            self.last_failed_files = 0
            facts_extracted = self._extract_all_facts(full_mode=full_mode, workers=workers, limit=limit)
            files_processed = getattr(self, "last_files_processed", 0)
            failed_files = getattr(self, "last_failed_files", 0)
            log_lines.append(f"  → Processed {files_processed} files, extracted {facts_extracted} new facts")
            if failed_files:
                log_lines.append(f"  ⚠ {failed_files} file(s) failed extraction and were NOT hashed; "
                                 f"they will be retried next run")

            # Gate: Steps 2-5 (derives, relation discovery, index rebuild, overview
            # generation) only have new material to chew on when extraction touched
            # at least one file. Running them every poll on an unchanged vault is the
            # expense the outer skill used to guard with a git-commit watermark — now
            # the content-hash result is the authoritative signal. --full/--clean/--force
            # always run the complete pipeline.
            if files_processed == 0 and not full_mode and not clean and not force:
                end_time = datetime.now()
                duration = (end_time - start_time).total_seconds()
                log_lines.append("  → No new/changed files; skipping relation, index, and overview steps")
                log_lines.append(f"\nNightly Extraction Complete (noop): {end_time.isoformat()} ({duration:.1f}s)")
                self.log_file.write_text("\n".join(log_lines))
                return {
                    "success": True,
                    "noop": True,
                    "files_processed": 0,
                    "facts_extracted": 0,
                    "failed_files": failed_files,
                    "total_relationships": None,
                    "overviews_generated": 0,
                    "duration_seconds": duration,
                }

            # Step 2: Index rebuild. `_infer_derives_relationships` and
            # `_discover_relations` used to sit here; both wrote into
            # relations-index.json (document-level co-occurrence), not the
            # entity graph, and `_discover_relations` compared only the first
            # 50 documents of 3,265 — an O(50²) sample presented as vault-wide
            # discovery. Edges now come from the extractor as it writes facts.
            log_lines.append("\n[Step 2] Index Rebuild")
            index = self.rel_generator.rebuild()
            log_lines.append(f"  → Rebuilt index with {index['total_relationships']} relationships")

            # Step 3: Entity overview generation (change-triggered)
            log_lines.append("\n[Step 3] Entity Overview Generation")
            overviews_generated = self._regenerate_entity_overviews()
            log_lines.append(f"  → Generated/updated {overviews_generated} entity overviews")

            # Summary
            end_time = datetime.now()
            duration = (end_time - start_time).total_seconds()
            log_lines.extend([
                f"\n{'='*60}",
                f"Nightly Extraction Complete: {end_time.isoformat()}",
                f"Duration: {duration:.1f} seconds",
                f"{'='*60}\n"
            ])

            # Write log
            self.log_file.write_text("\n".join(log_lines))

            return {
                "success": True,
                "noop": False,
                "files_processed": files_processed,
                "failed_files": failed_files,
                "duration_seconds": duration,
                "facts_extracted": facts_extracted,
                "total_relationships": index['total_relationships'],
                "overviews_generated": overviews_generated,
            }
            
        except Exception as e:
            log_lines.append(f"\nERROR: {str(e)}")
            self.log_file.write_text("\n".join(log_lines))
            raise
    
    def _process_single_file(self, md_file, full_mode, index, total):
        """Extract one file. Returns (processed, facts, ok).

        `ok=False` means the extraction failed and the caller must NOT save
        this file's content hash — otherwise a transient vLLM error marks the
        document done and it is never revisited.
        """
        processed = 0
        facts_count = 0

        try:
            raw = md_file.read_bytes()
        except OSError as e:
            print(f"Cannot read {md_file}: {e}")
            return 0, 0, False

        # Hash the bytes we actually extracted from. Re-hashing the file
        # afterwards records whatever it looks like then, so a note appended
        # to mid-run is marked extracted at content nobody read.
        source_hash = hash_bytes(raw)
        try:
            content = raw.decode("utf-8", errors="replace")
            doc_path = str(md_file.relative_to(VAULT))
        except ValueError:
            doc_path = str(md_file)

        try:
            result = self.extractor.extract_from_document(
                md_file, content, existing_facts=""
            )
        except ExtractionFailed as e:
            print(f"[{index}/{total}] FAILED: {doc_path}: {e}")
            return 0, 0, False
        except Exception as e:
            print(f"[{index}/{total}] ERROR: {doc_path}: {e}")
            return 0, 0, False

        try:
            if result.get("facts"):
                default_entity = result.get("entity") or "general"
                default_category = result.get("category") or "general"

                # Fan out: file each fact under its OWN entity/category (the
                # extractor tags every fact), so a multi-entity doc populates
                # multiple entity files instead of collapsing onto one primary.
                groups = {}
                for f in result["facts"]:
                    key = (f.get("entity") or default_entity,
                           f.get("category") or default_category)
                    groups.setdefault(key, []).append(f)

                for (entity, category), gfacts in groups.items():
                    self.extractor.write_fact_file(
                        entity, category,
                        {"entity": entity, "category": category, "facts": gfacts},
                        source_doc=doc_path,
                        source_hash=source_hash,
                    )
                    facts_count += len(gfacts)

                processed = 1
                print(f"[{index}/{total}] Processing: {doc_path} "
                      f"→ {len(groups)} entities, {facts_count} facts")
            else:
                # A genuinely factless document IS extracted; hashing it is
                # correct and stops it being re-read every night.
                processed = 1
        except Exception as e:
            print(f"Error writing facts for {md_file}: {e}")
            return 0, 0, False

        return processed, facts_count, True

    def _eligible_files(self, full_mode: bool) -> list:
        """The corpus, from `pipeline_config.yaml` `sources.paths`.

        This used to be `VAULT.rglob("*.md")` minus a list of deny-substrings,
        which is why the config file existed but was never read and why every
        new vault directory was ingested by default. Roughly half the 205k
        facts in the pre-2026-09 tree came from re-extracting the pipeline's
        own output. An allow-list inverts that: a directory is ingested
        because someone named it.

        The explicit excludes stay as belt-and-braces, and daily notes are
        only eligible once they are more than a day old — today's is appended
        to all day, so it never settles.
        """
        cfg = _load_pipeline_config()
        roots = []
        for raw in (cfg.get("sources", {}).get("paths") or []):
            path = Path(str(raw)).expanduser()
            if not path.is_absolute():
                path = VAULT / path
            try:
                path = path.resolve()
            except OSError:
                continue
            # Never leave the vault, whatever the config says.
            if path == VAULT or VAULT in path.parents:
                roots.append(path)
            else:
                print(f"  ⚠ sources.paths entry outside the vault, ignored: {raw}")
        if not roots:
            raise RuntimeError(
                "pipeline_config.yaml lists no usable sources.paths; refusing to "
                "fall back to the whole vault (that fallback is what fed the "
                "extractor its own output)"
            )
        excludes = tuple(cfg.get("sources", {}).get("exclude_patterns") or ())
        today = _TODAY_STR()
        cutoff_ok = lambda p: full_mode or (  # noqa: E731
            (datetime.now() - datetime.fromtimestamp(p.stat().st_mtime)).total_seconds() < 86400
        )

        eligible: list = []
        seen: set = set()
        for root in roots:
            if not root.exists():
                print(f"  ⚠ sources.paths entry does not exist: {root}")
                continue
            for md_file in root.rglob("*.md"):
                if not md_file.is_file() or md_file in seen:
                    continue
                path_str = str(md_file)
                if any(part in path_str for part in
                       ("node_modules", "/.venv", "/.cache", "/.git/", "__pycache__")):
                    continue
                if any(pat.strip("*/") and pat.strip("*/") in path_str for pat in excludes):
                    continue
                # Belt and braces: these never belong in the corpus even if a
                # sources.paths entry would otherwise reach them.
                if any(skip in path_str for skip in
                       ("/facts/", "/_pipeline/", "/skills/", "/agents/", "/autonomy/",
                        "/memory/vault-maintenance/")):
                    continue
                if md_file.name in _SELF_WRITTEN_MEMORY_NOTES:
                    continue
                # A daily note is appended to all day; it settles tomorrow.
                if md_file.parent.name == "memory" and md_file.stem >= today:
                    continue
                if not cutoff_ok(md_file):
                    continue
                seen.add(md_file)
                eligible.append(md_file)
        return eligible

    def _extract_all_facts(self, full_mode=False, workers=1, limit=0) -> int:
        """Extract facts from all documents."""
        total_facts = 0
        processed = 0
        failed = 0

        eligible_files = self._eligible_files(full_mode)

        total_files = len(eligible_files)
        print(f"Found {total_files} eligible files")

        # Filter by content hash - skip files already extracted (unchanged content).
        # Applied in BOTH window and full mode so --full is a resumable backfill that
        # skips already-done files rather than reprocessing the whole corpus.
        hasher = ContentHasher() if _HAS_HASHER else None
        if hasher is not None:
            changed_files = hasher.get_changed_files(eligible_files)
            skipped_unchanged = len(eligible_files) - len(changed_files)
            eligible_files = changed_files
            if skipped_unchanged > 0:
                print(f"Skipped {skipped_unchanged} unchanged files (content hash match)")

        # Optional per-run cap so a long backfill makes durable, bounded progress and
        # exits cleanly before the bash timeout (use with --full).
        if limit and limit > 0 and len(eligible_files) > limit:
            print(f"Limiting this run to {limit} of {len(eligible_files)} eligible files")
            eligible_files = eligible_files[:limit]

        # Incremental checkpoint: persist hashes for already-processed files every
        # CHECKPOINT_EVERY files so a timeout/kill never loses the whole run's work.
        CHECKPOINT_EVERY = 25
        pending: list = []

        def _flush_checkpoint():
            if hasher is not None and pending:
                try:
                    hasher.update_hashes(pending)
                    hasher.save()
                except Exception as e:
                    print(f"Warning: checkpoint failed: {e}")
                pending.clear()

        if workers == 1:
            # Sequential processing (default)
            for index, md_file in enumerate(eligible_files, 1):
                p, f, ok = self._process_single_file(md_file, full_mode, index, total_files)
                processed += p
                total_facts += f
                if ok:
                    # Only a file we actually extracted gets its hash saved.
                    # Hashing a failed file marks it done forever.
                    pending.append(md_file)
                else:
                    failed += 1
                if len(pending) >= CHECKPOINT_EVERY:
                    _flush_checkpoint()
        else:
            # Parallel processing
            with ThreadPoolExecutor(max_workers=workers) as executor:
                # Submit all tasks
                futures = {
                    executor.submit(self._process_single_file, md_file, full_mode, index, total_files):
                    (index, md_file)
                    for index, md_file in enumerate(eligible_files, 1)
                }

                # Collect results
                for future in as_completed(futures):
                    index, md_file = futures[future]
                    try:
                        p, f, ok = future.result()
                        processed += p
                        total_facts += f
                        if ok:
                            pending.append(md_file)
                        else:
                            failed += 1
                        if len(pending) >= CHECKPOINT_EVERY:
                            _flush_checkpoint()
                    except Exception as e:
                        failed += 1
                        print(f"Error processing {md_file}: {e}")

        print(f"Processed {processed} documents, extracted {total_facts} facts, {failed} failed")
        self.last_failed_files = failed

        # Final checkpoint for any remaining processed files
        _flush_checkpoint()
        if hasher is not None:
            print(f"Updated content hashes for {processed} processed files")

        # Expose file-processed count so run_full_extraction can gate the
        # expensive downstream steps on whether any new/changed file was seen.
        self.last_files_processed = processed
        return total_facts
    
    def _regenerate_entity_overviews(self) -> int:
        """Regenerate entity overview files whose source facts have changed."""
        return self.profile_generator.regenerate_all(workers=8)


def main():
    print("Nightly Deep Extraction - Next-Gen Memory")
    print("=" * 50)
    
    # Parse arguments
    parser = argparse.ArgumentParser(
        description="Nightly fact extraction for Next-Gen Memory System"
    )
    parser.add_argument(
        "--full",
        action="store_true",
        help="Process ALL files regardless of modification time (default: 24h window)"
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=1,
        help="Number of parallel workers (default: 1, sequential)"
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Wipe facts directory before extraction"
    )
    parser.add_argument(
        "--rebuild-index-only",
        action="store_true",
        help="Rebuild the document relations index and stop (no extraction)"
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Run the full downstream pipeline (relations/index/overviews) even "
             "when no new files were processed (overrides the noop short-circuit)."
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=0,
        help="Process at most N eligible files this run (0 = no cap). "
             "Use with --full for durable, bounded backfill that checkpoints "
             "progress and exits cleanly before the bash timeout."
    )

    args = parser.parse_args()
    
    extraction = NightlyExtraction()
    
    if args.rebuild_index_only:
        # Index only: no extraction
        print("Quick mode: rebuilding index...")
        index = extraction.rel_generator.rebuild()
        print(f"Total relationships: {index['total_relationships']}")
    else:
        # Full extraction with options
        result = extraction.run_full_extraction(
            full_mode=args.full,
            workers=args.workers,
            clean=args.clean,
            limit=args.limit,
            force=args.force,
        )
        print("\nResult:", json.dumps(result, indent=2))
        # Single-line, grep-friendly summary for the autonomy-data-pipeline skill's
        # gate. status=noop means nothing changed → caller should skip downstream work.
        print(
            f"PIPELINE_RESULT files_processed={result.get('files_processed', 0)} "
            f"facts={result.get('facts_extracted', 0)} "
            f"failed={result.get('failed_files', 0)} "
            f"status={'noop' if result.get('noop') else 'ran'}"
        )


if __name__ == "__main__":
    main()
