{   ((1, 8192), 0, 'inductor_standalone'): {   'cache_key': 'ackrmuteqeb75ys7nh33dil6pu2q33e3vsv43i5uzznihdvxu6mk',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_0',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_0')},
    ((1, 8192), 1, 'inductor_standalone'): {   'cache_key': 'aqavcv67cb7cdds5hvhggaq2cuhv2662xuz5nlgfczs6uhhlkq3m',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_1',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_1')},
    ((1, 8192), 2, 'inductor_standalone'): {   'cache_key': 'aneopyqr4bko5mx3nklfakckbtupp2tcmqz2jbl4oh4ulxedzhzi',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_2',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_2')},
    ((1, 8192), 3, 'inductor_standalone'): {   'cache_key': 'acvy43dcvqdm3mei7upyms3xwm5nd36h6c4xvxb7ujineforz6ko',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_3',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_3')},
    ((1, 8192), 4, 'inductor_standalone'): {   'cache_key': 'aql3g3tsecr7uihlkjvnjtexivhj4e7fin4wqcxr3y4zxqfohvev',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_4',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_4')},
    ((1, 8192), 5, 'inductor_standalone'): {   'cache_key': 'aa7mm4kxsbxkxcbusv2y4filmyvsmnyjlay3cbcgwayxv7bxtpdb',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_5',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_5')},
    ((1, 8192), 6, 'inductor_standalone'): {   'cache_key': 'acsxshd2fkcndbexbe72msgit4t5s57xvfo6hugljftlk37mcqz5',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_6',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_6')},
    ((1, 8192), 7, 'inductor_standalone'): {   'cache_key': 'afyxsy7fh4p4ny5xjydcessq75xwmml2nljnw63imj624nfwbzt2',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_7',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_7')},
    ((1, 8192), 9, 'inductor_standalone'): {   'cache_key': 'aauf7arh7mnpmice6sod366b6o3yaoupjhswm475l4bdtgd66wjg',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_9',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_9')},
    ((1, 8192), 10, 'inductor_standalone'): {   'cache_key': 'a6mbnje7p4g7a5kd57dgm663mcccrb24jww4eljuv7kvri7tqy55',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_10',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_10')},
    ((1, 8192), 11, 'inductor_standalone'): {   'cache_key': 'ajrd2rxwrojblaztr3emb5q2m3ar4egz5ev6owmfdu3yvhjlzlfa',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_11',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_11')},
    ((1, 8192), 13, 'inductor_standalone'): {   'cache_key': 'agvlw2eg5fhx52wq3dogtpnc4wu5pk36rzbtcveu6kp5wne3g5ij',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_13',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_13')},
    ((1, 8192), 14, 'inductor_standalone'): {   'cache_key': 'abevp7uigwakoeagqfx37pnx5rtutbh27nrjc6ktpl6qk3fjjvvs',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_14',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_14')},
    ((1, 8192), 15, 'inductor_standalone'): {   'cache_key': 'ai57to3och47e2qzbhk7y6lfnuugcvc5xpxgzwolehnt3rx2eg42',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_15',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_15')},
    ((1, 8192), 17, 'inductor_standalone'): {   'cache_key': 'ahmk5igiub7v4dzic45demhekdu5i2b34w4bjeogu62hovt7brhb',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_17',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_17')},
    ((1, 8192), 18, 'inductor_standalone'): {   'cache_key': 'akfnf2ezrkicegrimmhpp2lfjrnjqhjsvnwsalcwakoxijbnvvrn',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_18',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_18')},
    ((1, 8192), 19, 'inductor_standalone'): {   'cache_key': 'acoe5fie2lioy6nztg3gx4yguxmisyb2m6hksel7mqahl47yhsfs',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_19',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_19')},
    ((1, 8192), 21, 'inductor_standalone'): {   'cache_key': 'amhc4cot3pcyw2oup3jfjjzdolionxyr53xse7mn6rvlzbhqswa4',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_21',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_21')},
    ((1, 8192), 22, 'inductor_standalone'): {   'cache_key': 'avozlna3suw3y4e52jyfgc5hdvo57s7gbsb4cyssjpurjsrpy2n6',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_22',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_22')},
    ((1, 8192), 23, 'inductor_standalone'): {   'cache_key': 'a6uoeooi2zduspxwgsh7myhmy536eqmx2pgcbhjzdgrallw6iazu',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_23',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_23')},
    ((1, 8192), 25, 'inductor_standalone'): {   'cache_key': 'at7kanvd2x5kxpduslko6u2rtqjn7lprm7h6ai2molpavb2vxddn',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_25',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_25')},
    ((1, 8192), 26, 'inductor_standalone'): {   'cache_key': 'a33hvjxtwzuxpwcx2vg3ddrtmvawcafoyif7khcnzsp77lu34ag3',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_26',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_26')},
    ((1, 8192), 27, 'inductor_standalone'): {   'cache_key': 'ahyrzuccllbvjerwszblkojpbgvutie3ytavl5etngx4rb7uhc3y',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_27',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_27')},
    ((1, 8192), 29, 'inductor_standalone'): {   'cache_key': 'aegtectin2qc5qras7zhyrcrnbujapnvw6lc2bo3jd2vaclfsw4i',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_29',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_29')},
    ((1, 8192), 30, 'inductor_standalone'): {   'cache_key': 'auqn6cwo7rn76emlqp4vi77ciowvy3x7nc4xsylrn2gvmdulhvnf',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_30',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_30')},
    ((1, 8192), 31, 'inductor_standalone'): {   'cache_key': 'apwohqz4padkhjgsq36pcjffdbdlripw6qtgd6tz7ffjhnsxjg63',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_31',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_31')},
    ((1, 8192), 33, 'inductor_standalone'): {   'cache_key': 'axchjkdiki4vxpsu4xuwl4fztbkrp2cdlc6b4psivpsgtn7whll4',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_33',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_33')},
    ((1, 8192), 34, 'inductor_standalone'): {   'cache_key': 'ax7qp22gmqvr67f4kgsb2c4764ruqvlccqyi6sxfpvmroxglkohz',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_34',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_34')},
    ((1, 8192), 35, 'inductor_standalone'): {   'cache_key': 'amaqqrs5nibmxegrkq6p43yukcr24ytg5oh5pm3r6pnmxa2b6tra',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_35',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_35')},
    ((1, 8192), 37, 'inductor_standalone'): {   'cache_key': 'arfoulxskcj3q5gupxc4pywmoomdpmhbtx6ozdqwgawefijqepue',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_37',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_37')},
    ((1, 8192), 38, 'inductor_standalone'): {   'cache_key': 'afpx65c7g42wvfrkub4lg2g5pqldwacbtsfbigsluqeucyvfxfjj',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_38',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_38')},
    ((1, 8192), 39, 'inductor_standalone'): {   'cache_key': 'a62y33ow2rxyof3x6on5pziemiqdcyvldskjacvsydq3mk6vglj3',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_39',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_39')},
    ((1, 8192), 41, 'inductor_standalone'): {   'cache_key': 'aars5bcywx2exrybpeus4v3zpwkt5ns3ne426llsseqn64dp7u6n',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_41',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_41')},
    ((1, 8192), 42, 'inductor_standalone'): {   'cache_key': 'adyrhuxpfo3a3xglusgws2r5uzbgkysggaoqm2vueaxuu7zgf5na',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_42',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_42')},
    ((1, 8192), 43, 'inductor_standalone'): {   'cache_key': 'auvp6wfa3ekmdj43rzszng3u3ao6fkhhg5akajuxiex2otguxmrz',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_43',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_43')},
    ((1, 8192), 45, 'inductor_standalone'): {   'cache_key': 'azp4a3eoyhqcl7mqziycmo3rtjtwlhbypaeq5hoe7edy77rrmnzy',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_45',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_45')},
    ((1, 8192), 46, 'inductor_standalone'): {   'cache_key': 'a2dagixfd2rvkor65ddkucynuc3yawkhtyuh7d3jby337gjesjj7',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_46',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_46')},
    ((1, 8192), 47, 'inductor_standalone'): {   'cache_key': 'apjtkuwasnzs6fir7adqeyi6bk7pr6mqgkhbl2gwuxpylgzzpjkc',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_47',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_47')},
    ((1, 8192), 48, 'inductor_standalone'): {   'cache_key': 'a45bo7yxomc3bg2orggcvo7ojxpzec47gq6lwoorhzam6ftm6s2o',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_48',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/898d1ff202/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_48')}}