{   ((1, 8192), 0, 'inductor_standalone'): {   'cache_key': 'arfoerpibzaxuvyleoptq5mp66x3gnqc2b7bwntw5zntd7ud5gw4',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_0',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/9ad5db0ea8/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_0')},
    ((1, 8192), 1, 'inductor_standalone'): {   'cache_key': 'ajpetfslalg6yxvrneuqvvumbdvycdhdih6rll7a3f46vakms3ar',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_1',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/9ad5db0ea8/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_1')},
    ((1, 8192), 5, 'inductor_standalone'): {   'cache_key': 'atijgxsur5spnysq7xm4qf5wtkxd5rli6ie6rh3kinliy2l226b2',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_5',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/9ad5db0ea8/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_5')},
    ((1, 8192), 6, 'inductor_standalone'): {   'cache_key': 'ai7no7a2uwgw2ef3wddoilope6gcyl5ujvqkfzf7kjclxkvfloqt',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_6',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/9ad5db0ea8/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_6')},
    ((1, 8192), 24, 'inductor_standalone'): {   'cache_key': 'azc33pqbmbc7uqmw3q4b57joh3qoniiy7g3lbikiosparotzzx4e',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_24',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/9ad5db0ea8/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_24')},
    ((1, 8192), 25, 'inductor_standalone'): {   'cache_key': 'abd6qs7elol5dg7givjoobbdltwoghq3divdisud6hnce7s5mry6',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_25',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/9ad5db0ea8/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_25')},
    ((1, 8192), 29, 'inductor_standalone'): {   'cache_key': 'alsbuxgqz6cslr4lofcajsmig64bqyfubbzun54l3flo2bsso7gk',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_29',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/9ad5db0ea8/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_29')},
    ((1, 8192), 42, 'inductor_standalone'): {   'cache_key': 'akzpaxoewkd5apf44dxwq7vg5lbmu5dtao5adi6bxsfiihxsylck',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_42',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/9ad5db0ea8/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_42')}}