#!/usr/bin/env python3
"""One-off: rebuild INDEX.md from candidate frontmatter, matching mine-trajectories.py format."""
import re
import glob
import os
from datetime import datetime, timezone

cdir = os.path.expanduser("~/lloyd/_pipeline/skills/candidates")
candidates = sorted(os.path.basename(p) for p in glob.glob(os.path.join(cdir, "candidate-*.md")))

error_count = sum(1 for c in candidates if "error" in c and "seq-" not in c)
sequence_count = sum(1 for c in candidates if c.startswith("candidate-seq-"))
success_count = len(candidates) - error_count - sequence_count

content = f"""# Skill Candidates Index

This index tracks all skill candidates discovered through trajectory mining.
Generated by `mine-trajectories.py`.

## Summary

- **Total candidates:** {len(candidates)}
- **Error patterns:** {error_count}
- **Success patterns:** {success_count}
- **Sequence patterns:** {sequence_count}
- **Last updated:** {datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}

## Candidates

"""

for candidate in candidates:
    filepath = os.path.join(cdir, candidate)
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            first_lines = []
            in_frontmatter = False
            for line in f:
                first_lines.append(line)
                if line.strip() == '---' and len(first_lines) > 1:
                    if not in_frontmatter:
                        in_frontmatter = True
                    else:
                        break
        frontmatter = ''.join(first_lines)
        pattern_match = re.search(r'pattern:\s*(\S+)', frontmatter)
        pattern = pattern_match.group(1) if pattern_match else "unknown"
        sessions_match = re.search(r'sessions:\s*(\d+)', frontmatter)
        sessions = sessions_match.group(1) if sessions_match else "?"
        status_match = re.search(r'status:\s*(\S+)', frontmatter)
        status = status_match.group(1) if status_match else "?"
        content += f"- [{candidate}]({candidate}) — Pattern: `{pattern}` — Sessions: {sessions} — Status: {status}\n"
    except Exception:
        content += f"- [{candidate}]({candidate}) — (could not parse)\n"

content += """
## Generation Commands

```bash
# Show statistics without writing files
python3 ~/lloyd/scripts/mine-trajectories.py --stats

# Generate candidates for last 7 days (worker agent only)
python3 ~/lloyd/scripts/mine-trajectories.py --days 7 --agent worker --threshold 2

# Generate for all agents
python3 ~/lloyd/scripts/mine-trajectories.py --days 7 --agent all --threshold 2

# Custom output directory
python3 ~/lloyd/scripts/mine-trajectories.py --days 7 --output-dir ~/custom/output/
```

"""

with open(os.path.join(cdir, "INDEX.md"), "w", encoding="utf-8") as f:
    f.write(content)
print(f"INDEX.md rebuilt: {len(candidates)} candidates ({error_count} error, {success_count} success, {sequence_count} sequence)")
