"""The tools the MCP pool serves, as a committed snapshot (#2269).

A worker source's declared capability set is checked against this at
import, so a typo in a declared name is an exception at boot rather
than a tool that quietly stops being reachable — the failure mode an
allow-list has that a deny-list does not. Nothing else in the tree
enumerates the served set without a live pool: discovery happens
inside a turn, after the routers have built their options.

GENERATED — do not hand-edit:
    cd ~/lloyd && .venvs/lloyd/bin/python -m scripts.refresh_tool_roster

Two known stalenesses, both deliberate. A tool ADDED upstream is
absent until someone regenerates, so `registered_tool_names()` unions
this with the live discovery universe and a fresh name still passes.
A tool REMOVED upstream stays listed here, which only ever accepts a
declared name that then fails at dispatch — visible, not silent.
"""

from __future__ import annotations

REGISTERED_TOOLS: frozenset[str] = frozenset({
    "Bash",
    "ClearGoal",
    "Edit",
    "EnterPlanMode",
    "ExitPlanMode",
    "Glob",
    "Grep",
    "Read",
    "Scratchpad",
    "SetGoal",
    "Task",
    "TodoWrite",
    "Write",
    "_BackgroundTaskDrain",
    "ambient_decide",
    "automod_abort",
    "automod_amend_clause",
    "automod_gate",
    "automod_gate_wait",
    "automod_land",
    "automod_rollback",
    "automod_start",
    "automod_status",
    "automod_vault_land",
    "automod_vault_revert",
    "autonomy_config",
    "autonomy_config_set",
    "autonomy_delete_task",
    "autonomy_get_task",
    "autonomy_health",
    "autonomy_run_task",
    "autonomy_tasks",
    "autonomy_write_task",
    "autoresearch_rollback",
    "autoresearch_status",
    "backlog_boards",
    "backlog_get_task",
    "backlog_tasks",
    "backlog_write_task",
    "browser_click",
    "browser_cookies",
    "browser_drag",
    "browser_evaluate",
    "browser_fill",
    "browser_navigate",
    "browser_press",
    "browser_screenshot",
    "browser_scroll",
    "browser_select",
    "browser_snapshot",
    "browser_tabs",
    "browser_wait",
    "calendar_categories",
    "calendar_create",
    "calendar_delete_event",
    "calendar_events",
    "calendar_list",
    "calendar_update_event",
    "chat_get_session",
    "chat_list_sessions",
    "contacts_create",
    "contacts_delete",
    "contacts_get",
    "contacts_search",
    "contacts_update",
    "desktop_act",
    "desktop_capture",
    "discord_get_home_channel",
    "discord_list_channels",
    "discord_send",
    "discord_send_embed",
    "djev_decide",
    "djev_rank",
    "djev_status",
    "email_account_access",
    "email_accounts",
    "email_apply_filters",
    "email_create_filter",
    "email_create_folder",
    "email_delete",
    "email_delete_filter",
    "email_delete_folder",
    "email_display",
    "email_empty_junk",
    "email_empty_trash",
    "email_folders",
    "email_forward",
    "email_list_filters",
    "email_messages",
    "email_move_folder",
    "email_read",
    "email_recent",
    "email_rename_folder",
    "email_reorder_filters",
    "email_reply",
    "email_save_draft",
    "email_search",
    "email_send",
    "email_update",
    "email_update_filter",
    "fact_add",
    "fact_get",
    "fact_invalidate",
    "fact_relate",
    "fact_relationships",
    "fact_resolve",
    "fact_resolve_apply",
    "grant_create",
    "grant_list",
    "grant_revoke",
    "graph_affected",
    "graph_explain",
    "graph_hubs",
    "graph_path",
    "graph_refresh",
    "graph_status",
    "http_fetch",
    "http_request",
    "http_search",
    "ide_close_tab",
    "ide_open_file",
    "ide_open_folder",
    "mc_close_modal",
    "mc_get_state",
    "mc_navigate",
    "memory_add",
    "memory_read",
    "memory_remove",
    "memory_replace",
    "recall_observation",
    "research_complete",
    "research_list",
    "research_next",
    "research_propose",
    "research_stats",
    "session_inject_context",
    "session_recall",
    "skills_read",
    "skills_search",
    "tasks_create",
    "tasks_list",
    "tasks_update",
    "vault_overview",
    "vault_read",
    "vault_recall",
    "vault_search",
    "vault_write",
})

#: How many names the snapshot carries, for a drift message that does
#: not have to import the set to state a count.
REGISTERED_TOOL_COUNT = 147
