{   ((1, 8192), 0, 'inductor_standalone'): {   'cache_key': 'akdngcgnkc4u4xz77e65chwdan7wamgwgd6e2zmayemor7pw3s5q',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_0',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_0')},
    ((1, 8192), 1, 'inductor_standalone'): {   'cache_key': 'acqsso7d24iqyynt5pva5j5o73mq6jxr24eoonsexktf6vheqdw5',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_1',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_1')},
    ((1, 8192), 2, 'inductor_standalone'): {   'cache_key': 'apiokzbswt5yljnl3qaily63tbubuqc73mrym5e2ai2fzi7o3dto',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_2',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_2')},
    ((1, 8192), 3, 'inductor_standalone'): {   'cache_key': 'am5qtcbmubwhvw5ulbopyt2s4khmob732bla467ae5r37ennlh7j',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_3',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_3')},
    ((1, 8192), 4, 'inductor_standalone'): {   'cache_key': 'a45efzq6vvwkilfdiolejq45p4edegtck6ya4alvpih2xcmvgtmi',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_4',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_4')},
    ((1, 8192), 7, 'inductor_standalone'): {   'cache_key': 'arrud57vnygxwvhdacjxutlmwb6sb5hjaze2zkry2enpkwcq5sy5',
                                               'graph_handle': (   'artifact_compile_range_1_8192_subgraph_7',
                                                                   '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_7')},
    ((1, 8192), 11, 'inductor_standalone'): {   'cache_key': 'ajperwp2ejcrwr4gip2dzcrwudkgav5vzyxixeswkrgt4aiiatbj',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_11',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_11')},
    ((1, 8192), 15, 'inductor_standalone'): {   'cache_key': 'a44ymsadhcves6cpi7emqzuhv5ljt4bxvb24getlflp6ubbltqpy',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_15',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_15')},
    ((1, 8192), 19, 'inductor_standalone'): {   'cache_key': 'azrps3llbyvj3v2b2ln6c6wmwnksrmyetmae4vwrg6tz4rvie6yf',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_19',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_19')},
    ((1, 8192), 23, 'inductor_standalone'): {   'cache_key': 'arbkudzzcczjqtndy7ux7a2he3n26lq5segtzc74orm4ksu6cf4k',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_23',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_23')},
    ((1, 8192), 27, 'inductor_standalone'): {   'cache_key': 'a72obqo5bbodooomcv7tbv2qc7v6ky33pzbmmodqstlooul7majm',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_27',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_27')},
    ((1, 8192), 31, 'inductor_standalone'): {   'cache_key': 'a5j3animqbsvymb4sw3oyidn2xksqe2nq2nuulou7zpdk5hnk7br',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_31',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_31')},
    ((1, 8192), 35, 'inductor_standalone'): {   'cache_key': 'a6aboxjtt4ppo7lqtvmofloubjjz7ajyhz5d3zok2gubrunerop4',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_35',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_35')},
    ((1, 8192), 39, 'inductor_standalone'): {   'cache_key': 'anappopwr2zc552ge5424xc34abv5isxa5ooxclg3bmf23h4raye',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_39',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_39')},
    ((1, 8192), 43, 'inductor_standalone'): {   'cache_key': 'alvi3b4cg5vfrjuvulnhwdma6rmirfjym7vmh7uv52lakj73akej',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_43',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_43')},
    ((1, 8192), 47, 'inductor_standalone'): {   'cache_key': 'azvzlr3cmrmdw7ibmuh5hdjzwdve4bqysw7nccckkwzqj7x2opz6',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_47',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_47')},
    ((1, 8192), 51, 'inductor_standalone'): {   'cache_key': 'aiwc5m6rsggftqh3rtvwydpvqkzesxgka2f3oljblrmzv4qoecq2',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_51',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_51')},
    ((1, 8192), 55, 'inductor_standalone'): {   'cache_key': 'ah2sfbzhxdqtbtq34hroqjasxt3qzd5f2dmr2qdlrzt2dycnaqd7',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_55',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_55')},
    ((1, 8192), 59, 'inductor_standalone'): {   'cache_key': 'abnrtpeukk4nidnxtxmm4gopaomobytnynmigxxie6nbzvfuja4q',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_59',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_59')},
    ((1, 8192), 63, 'inductor_standalone'): {   'cache_key': 'a43i3fbvj4vbzgjsyvsxdmc6ppkrrwba46tw72ljlnapr34eon7v',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_63',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_63')},
    ((1, 8192), 64, 'inductor_standalone'): {   'cache_key': 'atzk2pqjcf3nzajhw5e4sk4z3ak6avqbsxcopt6guz4agwj55225',
                                                'graph_handle': (   'artifact_compile_range_1_8192_subgraph_64',
                                                                    '/home/alansrobotlab/.cache/vllm/torch_compile_cache/1dd7ec49ec/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_64')}}